### ISSUE TITLE
After scan the qr code i got this and script ends

### ISSUE THREAD

**Issue by vinayakvasu** [nian88/whatsapp-api#1]
connection update { isNewLogin: true, qr: undefined }
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (restart required)
        at WebSocket.<anonymous> (/root/whatsapp-dev/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:13)
        at WebSocket.emit (events.js:400:28)
        at /root/whatsapp-dev/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:219:35
        at Object.decodeFrame (/root/whatsapp-dev/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
        at WebSocket.onMessageRecieved (/root/whatsapp-dev/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:195:15)
        at WebSocket.emit (events.js:400:28)
        at Receiver.receiverOnMessage (/root/whatsapp-dev/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1169:20)
        at Receiver.emit (events.js:400:28)
        at Receiver.dataMessage (/root/whatsapp-dev/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)
        at Receiver.getData (/root/whatsapp-dev/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: true,
      output: [Object]
    },
    date: 2022-06-20T03:30:44.708Z
  }
}

**Comment by nian88** [comment]
restart your process
