### ISSUE TITLE
Error Appears After Scan

### ISSUE THREAD

**Issue by rudipratm** [nian88/whatsapp-api#2]
So I was doing the exact things **Instalasi** told me, and after scanning the QR Code I got these error:
```
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: ENOENT: no such file or directory, open './auth/auth.json'
        at Object.openSync (node:fs:505:3)
        at writeFileSync (node:fs:1535:35)
        at EventEmitter.saveState (C:\Workspace\whatsapp-api-main\node_modules\@adiwajshing\baileys\lib\Utils\use-single-file-auth-state.js:31:9)
        at EventEmitter.emit (node:events:381:22)
        at WebSocket.<anonymous> (C:\Workspace\whatsapp-api-main\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:393:16)
        at WebSocket.emit (node:events:369:20)
        at C:\Workspace\whatsapp-api-main\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:218:35
        at Object.decodeFrame (C:\Workspace\whatsapp-api-main\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:131:17)
        at WebSocket.onMessageRecieved (C:\Workspace\whatsapp-api-main\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:195:15)
        at WebSocket.emit (node:events:369:20) {
      errno: -4058,
      syscall: 'open',
      code: 'ENOENT',
      path: './auth/auth.json'
    },
    date: 2022-06-22T02:51:38.466Z
  }
}
```
![image](https://user-images.githubusercontent.com/48542234/174933301-78dae53c-3454-4d33-81d8-e1614b31c188.png)

**Comment by nian88** [comment]
Hmm. You can update in ./auth/auth.json to ./auth.json
