### ISSUE TITLE
Error: Stream Errored (conflict)

### ISSUE THREAD

**Issue by ArsaLabs** [nian88/whatsapp-api#8]
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
listening at http://0:3000
connection closed
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (conflict)
        at WebSocket.<anonymous> (F:\github\whatsapp-api\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:419:13)
        at WebSocket.emit (node:events:513:28)
        at F:\github\whatsapp-api\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:219:35
        at Object.decodeFrame (F:\github\whatsapp-api\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:131:17)
        at WebSocket.onMessageRecieved (F:\github\whatsapp-api\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:195:15)
        at WebSocket.emit (node:events:513:28)
        at Receiver.receiverOnMessage (F:\github\whatsapp-api\node_modules\ws\lib\websocket.js:1169:20)
        at Receiver.emit (node:events:513:28)
        at Receiver.dataMessage (F:\github\whatsapp-api\node_modules\ws\lib\receiver.js:513:14)
        at Receiver.getData (F:\github\whatsapp-api\node_modules\ws\lib\receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-12-12T12:53:32.462Z
  }
}

How fix it?

**Comment by nian88** [comment]
you can pull and run npm update

**Comment by ArsaLabs** [comment]
i did... the error still persistent

**Comment by nian88** [comment]
your node version and npm version?

**Comment by ArsaLabs** [comment]
node v16.17, npm v8.19
